flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- base-orphans-0.5.4
- bifunctors-5.3
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- hashable-1.2.4.0
- profunctors-5.2
- semigroups-0.18.1
- stm-2.4.4.1
- tagged-0.8.4
- text-1.2.2.1
- transformers-compat-0.5.1.4
- type-combinators-0.2.2.1
- unordered-containers-0.2.7.0
- void-0.7.1
resolver: ghc-7.10.2
