flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Glob-0.7.5
- StateVar-1.1.0.4
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-0.11.2.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- attoparsec-0.13.0.2
- base-orphans-0.5.4
- bifunctors-5.3
- blaze-builder-0.4.0.2
- cassava-0.4.5.0
- cereal-0.5.2.0
- comonad-5
- contravariant-1.4
- criterion-1.1.1.0
- distributive-0.5.0.2
- dlist-0.7.1.2
- erf-2.0.0.0
- fail-4.9.0.0
- hashable-1.2.4.0
- haskell-lexer-1.0
- hastache-0.6.1
- ieee754-0.7.8
- math-functions-0.1.7.0
- monad-par-0.3.4.7
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.4.0
- optparse-applicative-0.12.1.0
- parallel-3.2.1.0
- parsec-3.1.11
- pretty-show-1.6.10
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- scientific-0.3.4.6
- semigroups-0.18.1
- statistics-0.13.3.0
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.4
- text-1.2.2.1
- transformers-compat-0.5.1.4
- type-combinators-0.2.2.1
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.2
- vector-th-unbox-0.2.1.6
- void-0.7.1
resolver: ghc-7.10.2
